#!/bin/sh


doit() 
{
  sed "s/^\(.*\)'s\$/\1/"                   \
    | sort -u                               \
    | comm -12 - working/possessive.lst     \
    | sed "s/^\(.*\)/\1 \1's/"              \
    | tr ' ' '\n'
}

if [ "$1" ]
then
  cat $1 | doit > working/$$.postmp
  cat working/$$.postmp >> $1
  rm working/$$.postmp
else
  cat > $$.postmp
  cat $$.postmp | doit 
  cat $$.postmp
  rm $$.postmp
fi



