#!/bin/bash

if [ "$1" != -1 ]
then
  echo -n english ''
fi

echo american british british_z canadian australian variant_1 variant_2 variant_3 \
  british_variant_1 british_variant_2 canadian_variant_1 canadian_variant_2 australian_variant_1 australian_variant_2
