#!/bin/sh

rm -f working/*.$1.pre

comm -12 working/words.$1 working/american.lst \
  > working/american-all.$1.pre

comm -12 working/words.$1 working/british.lst \
  > working/british-all.$1.pre

comm -12 working/words.$1 working/british_z.lst \
  > working/british_z-all.$1.pre

comm -12 working/words.$1 working/canadian.lst \
  > working/canadian-all.$1.pre

comm -12 working/words.$1 working/australian.lst \
  > working/australian-all.$1.pre

comm -12 working/words.$1 working/variant_1.lst   \
  > working/variant_1-all.$1.pre

comm -12 working/words.$1 working/variant_2.lst   \
  > working/variant_2-all.$1.pre

comm -12 working/words.$1 working/variant_3.lst   \
  > working/variant_3-all.$1.pre

comm -12 working/words.$1 working/british_variant_1.lst   \
  > working/british_variant_1-all.$1.pre

comm -12 working/words.$1 working/british_variant_2.lst   \
  > working/british_variant_2-all.$1.pre

comm -12 working/words.$1 working/canadian_variant_1.lst   \
  > working/canadian_variant_1-all.$1.pre

comm -12 working/words.$1 working/canadian_variant_2.lst   \
  > working/canadian_variant_2-all.$1.pre

comm -12 working/words.$1 working/australian_variant_1.lst   \
  > working/australian_variant_1-all.$1.pre

comm -12 working/words.$1 working/australian_variant_2.lst   \
  > working/australian_variant_2-all.$1.pre

# Hack to get australian only words in
if [ $1 -eq 35 ]
then
  mv working/australian-all.$1.pre working/australian-all.$1.pre.pre
  cat r/special/australian.35 | src/filter \
    | cat - working/australian-all.$1.pre.pre | sort -u > working/australian-all.$1.pre
fi

cat working/*-all.$1.pre         \
  | sort | uniq                  \
  | comm -13 - working/words.$1  \
  > working/english-all.$1.pre

# Hack to get australian towns in
if [ $1 -eq 50 ]
then
  mv working/australian-all.$1.pre working/australian-all.$1.pre.pre
  cat r/special/australian-towns | src/add-possessive \
    | cat - r/special/australian-towns-part | src/filter \
    | sort -u \
    | comm -23 - working/english-all.$1.pre \
    | cat - working/australian-all.$1.pre.pre | sort -u > working/australian-all.$1.pre
fi

# Hack to get U.S. Urban areas in
if [ $1 -eq 50 ]
then
  mv working/american-all.$1.pre working/american-all.$1.pre.pre
  cat r/special/urban-areas | src/add-possessive \
    | src/filter \
    | sort -u \
    | comm -23 - working/english-all.$1.pre \
    | cat - working/american-all.$1.pre.pre | sort -u > working/american-all.$1.pre
fi

for s in `src/list-spellings`
do
  for c in `src/list-classes -1`
  do
    comm -12 working/$s-all.$1.pre working/$c.lst > working/$s-$c.$1.pre
    cat working/$s-$c.$1.pre >> working/$s-other.$1.pre
  done
  sort working/$s-other.$1.pre | uniq \
    | comm -13 - working/$s-all.$1.pre \
    > working/$s-words.$1.pre
  #rm working/$s-{all,other}.$1.pre
done






