
# generated file, must be kept in sync with constdata.sql

from ._common import SlotsDataClass

class PosInfo(SlotsDataClass):
    __slots__ = ('order_num', 'name', 'base_pos', 'descr', 'note', 'extra_info')

class BasePosInfo(SlotsDataClass):
    __slots__ = ('order_num', 'name', 'lemma_pos', 'category', 'descr', 'extra_info')

class SpellingInfo(SlotsDataClass):
    __slots__ = ('order_num', 'spelling', 'region', 'descr')

posInfo = {
  '?': PosInfo(order_num=1, name='?', base_pos='', descr='unknown', note=None, extra_info=None),
  'n0': PosInfo(order_num=4, name='n0', base_pos='n', descr='noun', note=None, extra_info=None),
  'ns': PosInfo(order_num=5, name='ns', base_pos='n', descr='noun: plural', note=None, extra_info=None),
  'nss': PosInfo(order_num=6, name='nss', base_pos='n', descr='noun: plural of plural', note=None, extra_info=None),
  'np': PosInfo(order_num=7, name='np', base_pos='n', descr='noun: possessive', note=None, extra_info=None),
  'nsp': PosInfo(order_num=8, name='nsp', base_pos='n', descr='noun: plural possessive', note=None, extra_info=None),
  'nssp': PosInfo(order_num=9, name='nssp', base_pos='n', descr='noun: plural of plural possessive', note=None, extra_info=None),
  'v0': PosInfo(order_num=10, name='v0', base_pos='v', descr='verb', note=None, extra_info=None),
  'vd': PosInfo(order_num=11, name='vd', base_pos='v', descr='verb: past tense (-ed)', note=None, extra_info=None),
  'vd2': PosInfo(order_num=12, name='vd2', base_pos='v', descr='verb: past tense plural (were)', note=None, extra_info=None),
  'vn': PosInfo(order_num=13, name='vn', base_pos='v', descr='verb: past participle (-en)', note=None, extra_info=None),
  'vg': PosInfo(order_num=14, name='vg', base_pos='v', descr='verb: present participle (-ing)', note=None, extra_info=None),
  'vs': PosInfo(order_num=15, name='vs', base_pos='v', descr='verb: present tense (-s)', note=None, extra_info=None),
  'vs2': PosInfo(order_num=16, name='vs2', base_pos='v', descr='verb: present tense second-person singular (are)', note=None, extra_info=None),
  'vs3': PosInfo(order_num=17, name='vs3', base_pos='v', descr='verb: present tense third-person singular (is)', note=None, extra_info=None),
  'vs4': PosInfo(order_num=18, name='vs4', base_pos='v', descr='verb: present tense plural (are)', note=None, extra_info=None),
  'm0': PosInfo(order_num=19, name='m0', base_pos='m', descr='noun/verb', note='n0 or v0', extra_info=None),
  'ms': PosInfo(order_num=20, name='ms', base_pos='m', descr='noun/verb: (-s)', note='ns or vs', extra_info=None),
  'aj0': PosInfo(order_num=21, name='aj0', base_pos='aj', descr='adjective', note=None, extra_info=None),
  'aj1': PosInfo(order_num=22, name='aj1', base_pos='aj', descr='adjective: comparative (-er)', note=None, extra_info=None),
  'aj2': PosInfo(order_num=23, name='aj2', base_pos='aj', descr='adjective: superlative (-est)', note=None, extra_info=None),
  'av0': PosInfo(order_num=24, name='av0', base_pos='av', descr='adverb', note=None, extra_info=None),
  'av1': PosInfo(order_num=25, name='av1', base_pos='av', descr='adverb: comparative (-er)', note=None, extra_info=None),
  'av2': PosInfo(order_num=26, name='av2', base_pos='av', descr='adverb: superlative (-est)', note=None, extra_info=None),
  'a0': PosInfo(order_num=27, name='a0', base_pos='a', descr='adjective/adverb', note='aj0 or av0', extra_info=None),
  'a1': PosInfo(order_num=28, name='a1', base_pos='a', descr='adjective/adverb: comparative (-er)', note='aj1 or av1', extra_info=None),
  'a2': PosInfo(order_num=29, name='a2', base_pos='a', descr='adjective/adverb: superlative (-est)', note='aj2 or av2', extra_info=None),
  'pn0': PosInfo(order_num=30, name='pn0', base_pos='pn', descr='pronoun', note=None, extra_info=None),
  'pn1': PosInfo(order_num=31, name='pn1', base_pos='pn', descr='pronoun: objective (you/him/her/...)', note=None, extra_info=None),
  'pns': PosInfo(order_num=32, name='pns', base_pos='pn', descr='pronoun: plural', note=None, extra_info=None),
  'pnd': PosInfo(order_num=33, name='pnd', base_pos='pn', descr='pronoun: determiner (your/his/her/...)', note=None, extra_info=None),
  'pnp': PosInfo(order_num=34, name='pnp', base_pos='pn', descr='pronoun: possessive (yours/his/hers/...)', note=None, extra_info=None),
  'pnr0': PosInfo(order_num=35, name='pnr0', base_pos='pn', descr='pronoun: reflexive singular (yourself/...)', note=None, extra_info=None),
  'pnrs': PosInfo(order_num=36, name='pnrs', base_pos='pn', descr='pronoun: reflexive plural (yourselves/...)', note=None, extra_info=None),
  'c': PosInfo(order_num=37, name='c', base_pos='c', descr='conjunction', note=None, extra_info=None),
  'pp': PosInfo(order_num=38, name='pp', base_pos='pp', descr='preposition', note=None, extra_info=None),
  'd': PosInfo(order_num=39, name='d', base_pos='d', descr='determiner', note=None, extra_info=None),
  'ds': PosInfo(order_num=40, name='ds', base_pos='d', descr='determiner: plural', note=None, extra_info=None),
  'd1': PosInfo(order_num=41, name='d1', base_pos='d', descr='determiner: comparative', note=None, extra_info=None),
  'd2': PosInfo(order_num=42, name='d2', base_pos='d', descr='determiner: superlative', note=None, extra_info=None),
  'i': PosInfo(order_num=43, name='i', base_pos='i', descr='interjection', note=None, extra_info=None),
  'abbr': PosInfo(order_num=44, name='abbr', base_pos='abbr', descr='abbreviation', note=None, extra_info=None),
  's': PosInfo(order_num=45, name='s', base_pos='s', descr='contraction', note=None, extra_info=None),
  'pre': PosInfo(order_num=46, name='pre', base_pos='pre', descr='prefix', note=None, extra_info=None),
  'suf': PosInfo(order_num=47, name='suf', base_pos='suf', descr='suffix', note=None, extra_info=None),
  'wp': PosInfo(order_num=48, name='wp', base_pos='wp', descr='multi-word part', note=None, extra_info=None),
  'we': PosInfo(order_num=49, name='we', base_pos='we', descr='multi-word ending', note=None, extra_info=None),
  'wes': PosInfo(order_num=50, name='wes', base_pos='we', descr='multi-word ending: plural', note=None, extra_info=None),
  'wep': PosInfo(order_num=51, name='wep', base_pos='we', descr='multi-word ending: possessive', note=None, extra_info=None),
  'weps': PosInfo(order_num=52, name='weps', base_pos='we', descr='multi-word ending: plural possessive', note=None, extra_info=None),
  'x': PosInfo(order_num=53, name='x', base_pos='x', descr='non word', note=None, extra_info='for example a roman numeral'),
}

basePosInfo = {
  '': BasePosInfo(order_num=1, name='', lemma_pos='?', category='', descr='unknown', extra_info=None),
  'n': BasePosInfo(order_num=2, name='n', lemma_pos='n0', category='', descr='noun', extra_info=None),
  'pl': BasePosInfo(order_num=3, name='pl', lemma_pos='ns', category='', descr='plural noun', extra_info=None),
  'v': BasePosInfo(order_num=4, name='v', lemma_pos='v0', category='', descr='verb', extra_info=None),
  'n_v': BasePosInfo(order_num=5, name='n_v', lemma_pos='m0', category='', descr='noun and verb', extra_info=None),
  'm': BasePosInfo(order_num=6, name='m', lemma_pos='m0', category='', descr='noun/verb', extra_info=None),
  'aj': BasePosInfo(order_num=7, name='aj', lemma_pos='aj0', category='', descr='adjective', extra_info=None),
  'av': BasePosInfo(order_num=8, name='av', lemma_pos='av0', category='', descr='adverb', extra_info=None),
  'aj_av': BasePosInfo(order_num=9, name='aj_av', lemma_pos='a0', category='', descr='adjective and adverb', extra_info=None),
  'a': BasePosInfo(order_num=10, name='a', lemma_pos='a0', category='', descr='adjective/adverb', extra_info=None),
  'pn': BasePosInfo(order_num=11, name='pn', lemma_pos='pn0', category='', descr='pronoun', extra_info=None),
  'c': BasePosInfo(order_num=12, name='c', lemma_pos='c', category='', descr='conjunction', extra_info=None),
  'pp': BasePosInfo(order_num=13, name='pp', lemma_pos='pp', category='', descr='preposition', extra_info=None),
  'd': BasePosInfo(order_num=14, name='d', lemma_pos='d', category='', descr='determiner', extra_info=None),
  'i': BasePosInfo(order_num=15, name='i', lemma_pos='i', category='', descr='interjection', extra_info=None),
  'abbr': BasePosInfo(order_num=16, name='abbr', lemma_pos='abbr', category='special', descr='abbreviation', extra_info=None),
  's': BasePosInfo(order_num=17, name='s', lemma_pos='s', category='special', descr='contraction', extra_info=None),
  'pre': BasePosInfo(order_num=18, name='pre', lemma_pos='pre', category='nonword', descr='prefix', extra_info=None),
  'suf': BasePosInfo(order_num=19, name='suf', lemma_pos='suf', category='nonword', descr='suffix', extra_info=None),
  'wp': BasePosInfo(order_num=20, name='wp', lemma_pos='wp', category='wordpart', descr='multi-word part', extra_info=None),
  'we': BasePosInfo(order_num=21, name='we', lemma_pos='we', category='wordpart', descr='multi-word ending', extra_info=None),
  'x': BasePosInfo(order_num=22, name='x', lemma_pos='x', category='nonword', descr='non word', extra_info='for example a roman numeral'),
}

fixPos = {
  ('', '?'): '?',
  ('', 'a0'): '?',
  ('', 'abbr'): '?',
  ('', 'aj0'): '?',
  ('', 'av0'): '?',
  ('', 'c'): '?',
  ('', 'd'): '?',
  ('', 'i'): '?',
  ('', 'm0'): '?',
  ('', 'n0'): '?',
  ('', 'pn0'): '?',
  ('', 'pp'): '?',
  ('', 'pre'): '?',
  ('', 's'): '?',
  ('', 'suf'): '?',
  ('', 'v0'): '?',
  ('', 'we'): '?',
  ('', 'wp'): '?',
  ('', 'x'): '?',
  ('a', '?'): 'a0',
  ('a', 'a0'): 'a0',
  ('a', 'a1'): 'a1',
  ('a', 'a2'): 'a2',
  ('a', 'abbr'): 'a0',
  ('a', 'aj0'): 'a0',
  ('a', 'aj1'): 'a1',
  ('a', 'aj2'): 'a2',
  ('a', 'av0'): 'a0',
  ('a', 'av1'): 'a1',
  ('a', 'av2'): 'a2',
  ('a', 'c'): 'a0',
  ('a', 'd'): 'a0',
  ('a', 'd1'): 'a1',
  ('a', 'd2'): 'a2',
  ('a', 'i'): 'a0',
  ('a', 'm0'): 'a0',
  ('a', 'n0'): 'a0',
  ('a', 'pn0'): 'a0',
  ('a', 'pp'): 'a0',
  ('a', 'pre'): 'a0',
  ('a', 's'): 'a0',
  ('a', 'suf'): 'a0',
  ('a', 'v0'): 'a0',
  ('a', 'we'): 'a0',
  ('a', 'wp'): 'a0',
  ('a', 'x'): 'a0',
  ('abbr', '?'): 'abbr',
  ('abbr', 'a0'): 'abbr',
  ('abbr', 'abbr'): 'abbr',
  ('abbr', 'aj0'): 'abbr',
  ('abbr', 'av0'): 'abbr',
  ('abbr', 'c'): 'abbr',
  ('abbr', 'd'): 'abbr',
  ('abbr', 'i'): 'abbr',
  ('abbr', 'm0'): 'abbr',
  ('abbr', 'n0'): 'abbr',
  ('abbr', 'pn0'): 'abbr',
  ('abbr', 'pp'): 'abbr',
  ('abbr', 'pre'): 'abbr',
  ('abbr', 's'): 'abbr',
  ('abbr', 'suf'): 'abbr',
  ('abbr', 'v0'): 'abbr',
  ('abbr', 'we'): 'abbr',
  ('abbr', 'wp'): 'abbr',
  ('abbr', 'x'): 'abbr',
  ('aj', '?'): 'aj0',
  ('aj', 'a0'): 'aj0',
  ('aj', 'a1'): 'aj1',
  ('aj', 'a2'): 'aj2',
  ('aj', 'abbr'): 'aj0',
  ('aj', 'aj0'): 'aj0',
  ('aj', 'aj1'): 'aj1',
  ('aj', 'aj2'): 'aj2',
  ('aj', 'av0'): 'aj0',
  ('aj', 'av1'): 'aj1',
  ('aj', 'av2'): 'aj2',
  ('aj', 'c'): 'aj0',
  ('aj', 'd'): 'aj0',
  ('aj', 'd1'): 'aj1',
  ('aj', 'd2'): 'aj2',
  ('aj', 'i'): 'aj0',
  ('aj', 'm0'): 'aj0',
  ('aj', 'n0'): 'aj0',
  ('aj', 'pn0'): 'aj0',
  ('aj', 'pp'): 'aj0',
  ('aj', 'pre'): 'aj0',
  ('aj', 's'): 'aj0',
  ('aj', 'suf'): 'aj0',
  ('aj', 'v0'): 'aj0',
  ('aj', 'we'): 'aj0',
  ('aj', 'wp'): 'aj0',
  ('aj', 'x'): 'aj0',
  ('av', '?'): 'av0',
  ('av', 'a0'): 'av0',
  ('av', 'a1'): 'av1',
  ('av', 'a2'): 'av2',
  ('av', 'abbr'): 'av0',
  ('av', 'aj0'): 'av0',
  ('av', 'aj1'): 'av1',
  ('av', 'aj2'): 'av2',
  ('av', 'av0'): 'av0',
  ('av', 'av1'): 'av1',
  ('av', 'av2'): 'av2',
  ('av', 'c'): 'av0',
  ('av', 'd'): 'av0',
  ('av', 'd1'): 'av1',
  ('av', 'd2'): 'av2',
  ('av', 'i'): 'av0',
  ('av', 'm0'): 'av0',
  ('av', 'n0'): 'av0',
  ('av', 'pn0'): 'av0',
  ('av', 'pp'): 'av0',
  ('av', 'pre'): 'av0',
  ('av', 's'): 'av0',
  ('av', 'suf'): 'av0',
  ('av', 'v0'): 'av0',
  ('av', 'we'): 'av0',
  ('av', 'wp'): 'av0',
  ('av', 'x'): 'av0',
  ('c', '?'): 'c',
  ('c', 'a0'): 'c',
  ('c', 'abbr'): 'c',
  ('c', 'aj0'): 'c',
  ('c', 'av0'): 'c',
  ('c', 'c'): 'c',
  ('c', 'd'): 'c',
  ('c', 'i'): 'c',
  ('c', 'm0'): 'c',
  ('c', 'n0'): 'c',
  ('c', 'pn0'): 'c',
  ('c', 'pp'): 'c',
  ('c', 'pre'): 'c',
  ('c', 's'): 'c',
  ('c', 'suf'): 'c',
  ('c', 'v0'): 'c',
  ('c', 'we'): 'c',
  ('c', 'wp'): 'c',
  ('c', 'x'): 'c',
  ('d', '?'): 'd',
  ('d', 'a0'): 'd',
  ('d', 'a1'): 'd1',
  ('d', 'a2'): 'd2',
  ('d', 'abbr'): 'd',
  ('d', 'aj0'): 'd',
  ('d', 'aj1'): 'd1',
  ('d', 'aj2'): 'd2',
  ('d', 'av0'): 'd',
  ('d', 'av1'): 'd1',
  ('d', 'av2'): 'd2',
  ('d', 'c'): 'd',
  ('d', 'd'): 'd',
  ('d', 'd1'): 'd1',
  ('d', 'd2'): 'd2',
  ('d', 'ds'): 'ds',
  ('d', 'i'): 'd',
  ('d', 'm0'): 'd',
  ('d', 'ms'): 'ds',
  ('d', 'n0'): 'd',
  ('d', 'ns'): 'ds',
  ('d', 'pn0'): 'd',
  ('d', 'pns'): 'ds',
  ('d', 'pp'): 'd',
  ('d', 'pre'): 'd',
  ('d', 's'): 'd',
  ('d', 'suf'): 'd',
  ('d', 'v0'): 'd',
  ('d', 'vs'): 'ds',
  ('d', 'we'): 'd',
  ('d', 'wes'): 'ds',
  ('d', 'wp'): 'd',
  ('d', 'x'): 'd',
  ('i', '?'): 'i',
  ('i', 'a0'): 'i',
  ('i', 'abbr'): 'i',
  ('i', 'aj0'): 'i',
  ('i', 'av0'): 'i',
  ('i', 'c'): 'i',
  ('i', 'd'): 'i',
  ('i', 'i'): 'i',
  ('i', 'm0'): 'i',
  ('i', 'n0'): 'i',
  ('i', 'pn0'): 'i',
  ('i', 'pp'): 'i',
  ('i', 'pre'): 'i',
  ('i', 's'): 'i',
  ('i', 'suf'): 'i',
  ('i', 'v0'): 'i',
  ('i', 'we'): 'i',
  ('i', 'wp'): 'i',
  ('i', 'x'): 'i',
  ('m', '?'): 'm0',
  ('m', 'a0'): 'm0',
  ('m', 'abbr'): 'm0',
  ('m', 'aj0'): 'm0',
  ('m', 'av0'): 'm0',
  ('m', 'c'): 'm0',
  ('m', 'd'): 'm0',
  ('m', 'ds'): 'ms',
  ('m', 'i'): 'm0',
  ('m', 'm0'): 'm0',
  ('m', 'ms'): 'ms',
  ('m', 'n0'): 'm0',
  ('m', 'ns'): 'ms',
  ('m', 'pn0'): 'm0',
  ('m', 'pns'): 'ms',
  ('m', 'pp'): 'm0',
  ('m', 'pre'): 'm0',
  ('m', 's'): 'm0',
  ('m', 'suf'): 'm0',
  ('m', 'v0'): 'm0',
  ('m', 'vd'): 'vd',
  ('m', 'vg'): 'vg',
  ('m', 'vn'): 'vn',
  ('m', 'vs'): 'ms',
  ('m', 'we'): 'm0',
  ('m', 'wes'): 'ms',
  ('m', 'wp'): 'm0',
  ('m', 'x'): 'm0',
  ('n', '?'): 'n0',
  ('n', 'a0'): 'n0',
  ('n', 'abbr'): 'n0',
  ('n', 'aj0'): 'n0',
  ('n', 'av0'): 'n0',
  ('n', 'c'): 'n0',
  ('n', 'd'): 'n0',
  ('n', 'ds'): 'ns',
  ('n', 'i'): 'n0',
  ('n', 'm0'): 'n0',
  ('n', 'ms'): 'ns',
  ('n', 'n0'): 'n0',
  ('n', 'np'): 'np',
  ('n', 'ns'): 'ns',
  ('n', 'nsp'): 'nsp',
  ('n', 'nss'): 'nss',
  ('n', 'nssp'): 'nssp',
  ('n', 'pn0'): 'n0',
  ('n', 'pns'): 'ns',
  ('n', 'pp'): 'n0',
  ('n', 'pre'): 'n0',
  ('n', 's'): 'n0',
  ('n', 'suf'): 'n0',
  ('n', 'v0'): 'n0',
  ('n', 'vs'): 'ns',
  ('n', 'we'): 'n0',
  ('n', 'wep'): 'np',
  ('n', 'weps'): 'nsp',
  ('n', 'wes'): 'ns',
  ('n', 'wp'): 'n0',
  ('n', 'x'): 'n0',
  ('pn', '?'): 'pn0',
  ('pn', 'a0'): 'pn0',
  ('pn', 'abbr'): 'pn0',
  ('pn', 'aj0'): 'pn0',
  ('pn', 'av0'): 'pn0',
  ('pn', 'c'): 'pn0',
  ('pn', 'd'): 'pn0',
  ('pn', 'ds'): 'pns',
  ('pn', 'i'): 'pn0',
  ('pn', 'm0'): 'pn0',
  ('pn', 'ms'): 'pns',
  ('pn', 'n0'): 'pn0',
  ('pn', 'ns'): 'pns',
  ('pn', 'pn0'): 'pn0',
  ('pn', 'pn1'): 'pn1',
  ('pn', 'pnd'): 'pnd',
  ('pn', 'pnp'): 'pnp',
  ('pn', 'pnr0'): 'pnr0',
  ('pn', 'pnrs'): 'pnrs',
  ('pn', 'pns'): 'pns',
  ('pn', 'pp'): 'pn0',
  ('pn', 'pre'): 'pn0',
  ('pn', 's'): 'pn0',
  ('pn', 'suf'): 'pn0',
  ('pn', 'v0'): 'pn0',
  ('pn', 'vs'): 'pns',
  ('pn', 'we'): 'pn0',
  ('pn', 'wes'): 'pns',
  ('pn', 'wp'): 'pn0',
  ('pn', 'x'): 'pn0',
  ('pp', '?'): 'pp',
  ('pp', 'a0'): 'pp',
  ('pp', 'abbr'): 'pp',
  ('pp', 'aj0'): 'pp',
  ('pp', 'av0'): 'pp',
  ('pp', 'c'): 'pp',
  ('pp', 'd'): 'pp',
  ('pp', 'i'): 'pp',
  ('pp', 'm0'): 'pp',
  ('pp', 'n0'): 'pp',
  ('pp', 'pn0'): 'pp',
  ('pp', 'pp'): 'pp',
  ('pp', 'pre'): 'pp',
  ('pp', 's'): 'pp',
  ('pp', 'suf'): 'pp',
  ('pp', 'v0'): 'pp',
  ('pp', 'we'): 'pp',
  ('pp', 'wp'): 'pp',
  ('pp', 'x'): 'pp',
  ('pre', '?'): 'pre',
  ('pre', 'a0'): 'pre',
  ('pre', 'abbr'): 'pre',
  ('pre', 'aj0'): 'pre',
  ('pre', 'av0'): 'pre',
  ('pre', 'c'): 'pre',
  ('pre', 'd'): 'pre',
  ('pre', 'i'): 'pre',
  ('pre', 'm0'): 'pre',
  ('pre', 'n0'): 'pre',
  ('pre', 'pn0'): 'pre',
  ('pre', 'pp'): 'pre',
  ('pre', 'pre'): 'pre',
  ('pre', 's'): 'pre',
  ('pre', 'suf'): 'pre',
  ('pre', 'v0'): 'pre',
  ('pre', 'we'): 'pre',
  ('pre', 'wp'): 'pre',
  ('pre', 'x'): 'pre',
  ('s', '?'): 's',
  ('s', 'a0'): 's',
  ('s', 'abbr'): 's',
  ('s', 'aj0'): 's',
  ('s', 'av0'): 's',
  ('s', 'c'): 's',
  ('s', 'd'): 's',
  ('s', 'i'): 's',
  ('s', 'm0'): 's',
  ('s', 'n0'): 's',
  ('s', 'pn0'): 's',
  ('s', 'pp'): 's',
  ('s', 'pre'): 's',
  ('s', 's'): 's',
  ('s', 'suf'): 's',
  ('s', 'v0'): 's',
  ('s', 'we'): 's',
  ('s', 'wp'): 's',
  ('s', 'x'): 's',
  ('suf', '?'): 'suf',
  ('suf', 'a0'): 'suf',
  ('suf', 'abbr'): 'suf',
  ('suf', 'aj0'): 'suf',
  ('suf', 'av0'): 'suf',
  ('suf', 'c'): 'suf',
  ('suf', 'd'): 'suf',
  ('suf', 'i'): 'suf',
  ('suf', 'm0'): 'suf',
  ('suf', 'n0'): 'suf',
  ('suf', 'pn0'): 'suf',
  ('suf', 'pp'): 'suf',
  ('suf', 'pre'): 'suf',
  ('suf', 's'): 'suf',
  ('suf', 'suf'): 'suf',
  ('suf', 'v0'): 'suf',
  ('suf', 'we'): 'suf',
  ('suf', 'wp'): 'suf',
  ('suf', 'x'): 'suf',
  ('v', '?'): 'v0',
  ('v', 'a0'): 'v0',
  ('v', 'abbr'): 'v0',
  ('v', 'aj0'): 'v0',
  ('v', 'av0'): 'v0',
  ('v', 'c'): 'v0',
  ('v', 'd'): 'v0',
  ('v', 'ds'): 'vs',
  ('v', 'i'): 'v0',
  ('v', 'm0'): 'v0',
  ('v', 'ms'): 'vs',
  ('v', 'n0'): 'v0',
  ('v', 'ns'): 'vs',
  ('v', 'pn0'): 'v0',
  ('v', 'pns'): 'vs',
  ('v', 'pp'): 'v0',
  ('v', 'pre'): 'v0',
  ('v', 's'): 'v0',
  ('v', 'suf'): 'v0',
  ('v', 'v0'): 'v0',
  ('v', 'vd'): 'vd',
  ('v', 'vd2'): 'vd2',
  ('v', 'vg'): 'vg',
  ('v', 'vn'): 'vn',
  ('v', 'vs'): 'vs',
  ('v', 'vs2'): 'vs2',
  ('v', 'vs3'): 'vs3',
  ('v', 'vs4'): 'vs4',
  ('v', 'we'): 'v0',
  ('v', 'wes'): 'vs',
  ('v', 'wp'): 'v0',
  ('v', 'x'): 'v0',
  ('we', '?'): 'we',
  ('we', 'a0'): 'we',
  ('we', 'abbr'): 'we',
  ('we', 'aj0'): 'we',
  ('we', 'av0'): 'we',
  ('we', 'c'): 'we',
  ('we', 'd'): 'we',
  ('we', 'ds'): 'wes',
  ('we', 'i'): 'we',
  ('we', 'm0'): 'we',
  ('we', 'ms'): 'wes',
  ('we', 'n0'): 'we',
  ('we', 'np'): 'wep',
  ('we', 'ns'): 'wes',
  ('we', 'nsp'): 'weps',
  ('we', 'pn0'): 'we',
  ('we', 'pns'): 'wes',
  ('we', 'pp'): 'we',
  ('we', 'pre'): 'we',
  ('we', 's'): 'we',
  ('we', 'suf'): 'we',
  ('we', 'v0'): 'we',
  ('we', 'vs'): 'wes',
  ('we', 'we'): 'we',
  ('we', 'wep'): 'wep',
  ('we', 'weps'): 'weps',
  ('we', 'wes'): 'wes',
  ('we', 'wp'): 'we',
  ('we', 'x'): 'we',
  ('wp', '?'): 'wp',
  ('wp', 'a0'): 'wp',
  ('wp', 'abbr'): 'wp',
  ('wp', 'aj0'): 'wp',
  ('wp', 'av0'): 'wp',
  ('wp', 'c'): 'wp',
  ('wp', 'd'): 'wp',
  ('wp', 'i'): 'wp',
  ('wp', 'm0'): 'wp',
  ('wp', 'n0'): 'wp',
  ('wp', 'pn0'): 'wp',
  ('wp', 'pp'): 'wp',
  ('wp', 'pre'): 'wp',
  ('wp', 's'): 'wp',
  ('wp', 'suf'): 'wp',
  ('wp', 'v0'): 'wp',
  ('wp', 'we'): 'wp',
  ('wp', 'wp'): 'wp',
  ('wp', 'x'): 'wp',
  ('x', '?'): 'x',
  ('x', 'a0'): 'x',
  ('x', 'abbr'): 'x',
  ('x', 'aj0'): 'x',
  ('x', 'av0'): 'x',
  ('x', 'c'): 'x',
  ('x', 'd'): 'x',
  ('x', 'i'): 'x',
  ('x', 'm0'): 'x',
  ('x', 'n0'): 'x',
  ('x', 'pn0'): 'x',
  ('x', 'pp'): 'x',
  ('x', 'pre'): 'x',
  ('x', 's'): 'x',
  ('x', 'suf'): 'x',
  ('x', 'v0'): 'x',
  ('x', 'we'): 'x',
  ('x', 'wp'): 'x',
  ('x', 'x'): 'x',
}

variantAsSymbol = {0: '', 1: '.', 2: '=', 3: '?', 4: 'v', 5: '~', 6: 'V', 7: '-', 8: '@', 9: 'x'}

variantFromSymbol = {'': 0, '.': 1, '=': 2, '?': 3, 'v': 4, '~': 5, 'V': 6, '-': 7, '@': 8, 'x': 9}

spellingInfo = {
  '_': SpellingInfo(order_num=1, spelling='_', region='', descr=''),
  'A': SpellingInfo(order_num=2, spelling='A', region='US', descr='American'),
  'B': SpellingInfo(order_num=3, spelling='B', region='GB', descr='British(ise)'),
  'Z': SpellingInfo(order_num=4, spelling='Z', region='GB', descr='British(ize)'),
  'C': SpellingInfo(order_num=5, spelling='C', region='CA', descr='Canadian'),
  'D': SpellingInfo(order_num=6, spelling='D', region='AU', descr='Australian'),
}

SPELLINGS = ('_', 'A', 'B', 'Z', 'C', 'D')

REGIONS = ('', 'US', 'GB', 'CA', 'AU')

POS_CATEGORIES = ('', 'nonword', 'special', 'wordpart')


