BEGIN;
INSERT INTO poses VALUES(1,'?','','placeholder','unknown',NULL,NULL);
INSERT INTO poses VALUES(2,'c','c','','conjunction/preposition',NULL,NULL);
INSERT INTO poses VALUES(3,'i','i','','interjection',NULL,NULL);
INSERT INTO poses VALUES(4,'p','p','','pronoun',NULL,NULL);
INSERT INTO poses VALUES(5,'s','s','special','contraction',NULL,NULL);
INSERT INTO poses VALUES(6,'n0','n','',NULL,NULL,NULL);
INSERT INTO poses VALUES(7,'ns','n','','plural',NULL,NULL);
INSERT INTO poses VALUES(8,'np','n','','possessive',NULL,NULL);
INSERT INTO poses VALUES(9,'nsp','n','','plural possessive',NULL,NULL);
INSERT INTO poses VALUES(10,'v0','v','',NULL,NULL,NULL);
INSERT INTO poses VALUES(11,'vd','v','','past tense (-ed)',NULL,NULL);
INSERT INTO poses VALUES(12,'vd2','v','','past tense plural',NULL,NULL);
INSERT INTO poses VALUES(13,'vn','v','','past participle',NULL,NULL);
INSERT INTO poses VALUES(14,'vg','v','','present participle (-ing)',NULL,NULL);
INSERT INTO poses VALUES(15,'vs','v','','present tense (-s)',NULL,NULL);
INSERT INTO poses VALUES(16,'vs2','v','','present tense second-person singular',NULL,NULL);
INSERT INTO poses VALUES(17,'vs3','v','','present tense third-person singular',NULL,NULL);
INSERT INTO poses VALUES(18,'vs4','v','','present tense plural',NULL,NULL);
INSERT INTO poses VALUES(19,'m0','m','',NULL,'n0 or v0',NULL);
INSERT INTO poses VALUES(20,'ms','m','','(-s)','ns or vs',NULL);
INSERT INTO poses VALUES(21,'aj0','aj','',NULL,NULL,NULL);
INSERT INTO poses VALUES(22,'aj1','aj','','comparative (-er)',NULL,NULL);
INSERT INTO poses VALUES(23,'aj2','aj','','superlative (-est)',NULL,NULL);
INSERT INTO poses VALUES(24,'av0','av','',NULL,NULL,NULL);
INSERT INTO poses VALUES(25,'av1','av','','comparative (-er)',NULL,NULL);
INSERT INTO poses VALUES(26,'av2','av','','superlative (-est)',NULL,NULL);
INSERT INTO poses VALUES(27,'a0','a','',NULL,'aj0 or av0',NULL);
INSERT INTO poses VALUES(28,'a1','a','','comparative (-er)','aj1 or av1',NULL);
INSERT INTO poses VALUES(29,'a2','a','','superlative (-est)','aj2 or av2',NULL);
INSERT INTO poses VALUES(30,'pre','pre','wordpart','prefix',NULL,NULL);
INSERT INTO poses VALUES(31,'wp','wp','wordpart','multi-word part',NULL,NULL);
INSERT INTO poses VALUES(32,'we','we','wordpart','multi-word ending',NULL,NULL);
INSERT INTO poses VALUES(33,'wep','we','wordpart','possessive',NULL,NULL);
INSERT INTO poses VALUES(34,'abbr','abbr','special','abbreviation',NULL,NULL);
INSERT INTO poses VALUES(35,'x','x','special','non word',NULL,'for example a roman numeral');
INSERT INTO base_poses VALUES(1,'','?','','unknown',NULL);
INSERT INTO base_poses VALUES(2,'n_v','m0','','noun and verb',NULL);
INSERT INTO base_poses VALUES(3,'aj_av','a0','','adjective and adverb',NULL);
INSERT INTO base_poses VALUES(4,'n','n0','','noun',NULL);
INSERT INTO base_poses VALUES(5,'m','m0','','noun/verb',NULL);
INSERT INTO base_poses VALUES(6,'v','v0','','verb',NULL);
INSERT INTO base_poses VALUES(7,'aj','aj0','','adjective',NULL);
INSERT INTO base_poses VALUES(8,'av','av0','','adverb',NULL);
INSERT INTO base_poses VALUES(9,'a','a0','','adjective/adverb',NULL);
INSERT INTO base_poses VALUES(10,'c','c','','conjunction/preposition',NULL);
INSERT INTO base_poses VALUES(11,'i','i','','interjection',NULL);
INSERT INTO base_poses VALUES(12,'p','p','','pronoun',NULL);
INSERT INTO base_poses VALUES(13,'s','s','special','contraction',NULL);
INSERT INTO base_poses VALUES(14,'pre','pre','wordpart','prefix',NULL);
INSERT INTO base_poses VALUES(15,'wp','wp','wordpart','multi-word part',NULL);
INSERT INTO base_poses VALUES(16,'we','we','wordpart','multi-word ending',NULL);
INSERT INTO base_poses VALUES(17,'abbr','abbr','special','abbreviation',NULL);
INSERT INTO base_poses VALUES(18,'x','x','special','non word','for example a roman numeral');
INSERT INTO ranks VALUES(1,'','');
INSERT INTO ranks VALUES(2,'*','usage dependent');
INSERT INTO ranks VALUES(3,'-','uncommon');
INSERT INTO ranks VALUES(4,'@','archaic');
INSERT INTO ranks VALUES(5,'~','inapplicable');
INSERT INTO ranks VALUES(6,'!','infrequent');
INSERT INTO variant_levels VALUES(0,'','');
INSERT INTO variant_levels VALUES(1,'.','include');
INSERT INTO variant_levels VALUES(2,'=','equal');
INSERT INTO variant_levels VALUES(3,'?','disagreement');
INSERT INTO variant_levels VALUES(4,'v','common');
INSERT INTO variant_levels VALUES(5,'~','variant');
INSERT INTO variant_levels VALUES(6,'V','acceptable');
INSERT INTO variant_levels VALUES(8,'-','uncommon');
INSERT INTO variant_levels VALUES(9,'x','invalid');
INSERT INTO regions VALUES(1,'',NULL);
INSERT INTO regions VALUES(2,'US',NULL);
INSERT INTO regions VALUES(3,'GB',NULL);
INSERT INTO regions VALUES(4,'CA',NULL);
INSERT INTO regions VALUES(5,'AU',NULL);
INSERT INTO spellings VALUES(1,'_','','');
INSERT INTO spellings VALUES(2,'A','US','American');
INSERT INTO spellings VALUES(3,'B','GB','British(ise)');
INSERT INTO spellings VALUES(4,'Z','GB','British(ize)');
INSERT INTO spellings VALUES(5,'C','CA','Canadian');
INSERT INTO spellings VALUES(6,'D','AU','Australian');
END;
