BEGIN;
PRAGMA defer_foreign_keys = ON;
INSERT INTO poses VALUES(1,'?','','unknown',NULL,NULL);
INSERT INTO poses VALUES(27,'a0','a','adjective/adverb','aj0 or av0',NULL);
INSERT INTO poses VALUES(28,'a1','a','adjective/adverb: comparative (-er)','aj1 or av1',NULL);
INSERT INTO poses VALUES(29,'a2','a','adjective/adverb: superlative (-est)','aj2 or av2',NULL);
INSERT INTO poses VALUES(44,'abbr','abbr','abbreviation',NULL,NULL);
INSERT INTO poses VALUES(21,'aj0','aj','adjective',NULL,NULL);
INSERT INTO poses VALUES(22,'aj1','aj','adjective: comparative (-er)',NULL,NULL);
INSERT INTO poses VALUES(23,'aj2','aj','adjective: superlative (-est)',NULL,NULL);
INSERT INTO poses VALUES(24,'av0','av','adverb',NULL,NULL);
INSERT INTO poses VALUES(25,'av1','av','adverb: comparative (-er)',NULL,NULL);
INSERT INTO poses VALUES(26,'av2','av','adverb: superlative (-est)',NULL,NULL);
INSERT INTO poses VALUES(37,'c','c','conjunction',NULL,NULL);
INSERT INTO poses VALUES(39,'d','d','determiner',NULL,NULL);
INSERT INTO poses VALUES(41,'d1','d','determiner: comparative',NULL,NULL);
INSERT INTO poses VALUES(42,'d2','d','determiner: superlative',NULL,NULL);
INSERT INTO poses VALUES(40,'ds','d','determiner: plural',NULL,NULL);
INSERT INTO poses VALUES(43,'i','i','interjection',NULL,NULL);
INSERT INTO poses VALUES(19,'m0','m','noun/verb','n0 or v0',NULL);
INSERT INTO poses VALUES(20,'ms','m','noun/verb: (-s)','ns or vs',NULL);
INSERT INTO poses VALUES(4,'n0','n','noun',NULL,NULL);
INSERT INTO poses VALUES(7,'np','n','noun: possessive',NULL,NULL);
INSERT INTO poses VALUES(5,'ns','n','noun: plural',NULL,NULL);
INSERT INTO poses VALUES(8,'nsp','n','noun: plural possessive',NULL,NULL);
INSERT INTO poses VALUES(6,'nss','n','noun: plural of plural',NULL,NULL);
INSERT INTO poses VALUES(9,'nssp','n','noun: plural of plural possessive',NULL,NULL);
INSERT INTO poses VALUES(30,'pn0','pn','pronoun',NULL,NULL);
INSERT INTO poses VALUES(31,'pn1','pn','pronoun: objective (you/him/her/...)',NULL,NULL);
INSERT INTO poses VALUES(33,'pnd','pn','pronoun: determiner (your/his/her/...)',NULL,NULL);
INSERT INTO poses VALUES(34,'pnp','pn','pronoun: possessive (yours/his/hers/...)',NULL,NULL);
INSERT INTO poses VALUES(35,'pnr0','pn','pronoun: reflexive singular (yourself/...)',NULL,NULL);
INSERT INTO poses VALUES(36,'pnrs','pn','pronoun: reflexive plural (yourselves/...)',NULL,NULL);
INSERT INTO poses VALUES(32,'pns','pn','pronoun: plural',NULL,NULL);
INSERT INTO poses VALUES(38,'pp','pp','preposition',NULL,NULL);
INSERT INTO poses VALUES(46,'pre','pre','prefix',NULL,NULL);
INSERT INTO poses VALUES(45,'s','s','contraction',NULL,NULL);
INSERT INTO poses VALUES(47,'suf','suf','suffix',NULL,NULL);
INSERT INTO poses VALUES(10,'v0','v','verb',NULL,NULL);
INSERT INTO poses VALUES(11,'vd','v','verb: past tense (-ed)',NULL,NULL);
INSERT INTO poses VALUES(12,'vd2','v','verb: past tense plural (were)',NULL,NULL);
INSERT INTO poses VALUES(14,'vg','v','verb: present participle (-ing)',NULL,NULL);
INSERT INTO poses VALUES(13,'vn','v','verb: past participle (-en)',NULL,NULL);
INSERT INTO poses VALUES(15,'vs','v','verb: present tense (-s)',NULL,NULL);
INSERT INTO poses VALUES(16,'vs2','v','verb: present tense second-person singular (are)',NULL,NULL);
INSERT INTO poses VALUES(17,'vs3','v','verb: present tense third-person singular (is)',NULL,NULL);
INSERT INTO poses VALUES(18,'vs4','v','verb: present tense plural (are)',NULL,NULL);
INSERT INTO poses VALUES(49,'we','we','multi-word ending',NULL,NULL);
INSERT INTO poses VALUES(51,'wep','we','multi-word ending: possessive',NULL,NULL);
INSERT INTO poses VALUES(52,'weps','we','multi-word ending: plural possessive',NULL,NULL);
INSERT INTO poses VALUES(50,'wes','we','multi-word ending: plural',NULL,NULL);
INSERT INTO poses VALUES(48,'wp','wp','multi-word part',NULL,NULL);
INSERT INTO poses VALUES(53,'x','x','non word',NULL,'for example a roman numeral');
INSERT INTO base_poses VALUES(1,'','?','','unknown',NULL);
INSERT INTO base_poses VALUES(10,'a','a0','','adjective/adverb',NULL);
INSERT INTO base_poses VALUES(16,'abbr','abbr','special','abbreviation',NULL);
INSERT INTO base_poses VALUES(7,'aj','aj0','','adjective',NULL);
INSERT INTO base_poses VALUES(9,'aj_av','a0','','adjective and adverb',NULL);
INSERT INTO base_poses VALUES(8,'av','av0','','adverb',NULL);
INSERT INTO base_poses VALUES(12,'c','c','','conjunction',NULL);
INSERT INTO base_poses VALUES(14,'d','d','','determiner',NULL);
INSERT INTO base_poses VALUES(15,'i','i','','interjection',NULL);
INSERT INTO base_poses VALUES(6,'m','m0','','noun/verb',NULL);
INSERT INTO base_poses VALUES(2,'n','n0','','noun',NULL);
INSERT INTO base_poses VALUES(5,'n_v','m0','','noun and verb',NULL);
INSERT INTO base_poses VALUES(3,'pl','ns','','plural noun',NULL);
INSERT INTO base_poses VALUES(11,'pn','pn0','','pronoun',NULL);
INSERT INTO base_poses VALUES(13,'pp','pp','','preposition',NULL);
INSERT INTO base_poses VALUES(18,'pre','pre','nonword','prefix',NULL);
INSERT INTO base_poses VALUES(17,'s','s','special','contraction',NULL);
INSERT INTO base_poses VALUES(19,'suf','suf','nonword','suffix',NULL);
INSERT INTO base_poses VALUES(4,'v','v0','','verb',NULL);
INSERT INTO base_poses VALUES(21,'we','we','wordpart','multi-word ending',NULL);
INSERT INTO base_poses VALUES(20,'wp','wp','wordpart','multi-word part',NULL);
INSERT INTO base_poses VALUES(22,'x','x','nonword','non word','for example a roman numeral');
INSERT INTO ranks VALUES(1,'','');
INSERT INTO ranks VALUES(6,'!','infrequent');
INSERT INTO ranks VALUES(2,'*','usage dependent');
INSERT INTO ranks VALUES(3,'-','uncommon');
INSERT INTO ranks VALUES(4,'@','archaic');
INSERT INTO ranks VALUES(5,'~','inapplicable');
INSERT INTO variant_levels VALUES(0,'','',0);
INSERT INTO variant_levels VALUES(1,'.','include',0);
INSERT INTO variant_levels VALUES(2,'=','equal',1);
INSERT INTO variant_levels VALUES(3,'?','disagreement',1);
INSERT INTO variant_levels VALUES(4,'v','common',1);
INSERT INTO variant_levels VALUES(5,'~','variant',2);
INSERT INTO variant_levels VALUES(6,'V','acceptable',2);
INSERT INTO variant_levels VALUES(7,'-','uncommon',3);
INSERT INTO variant_levels VALUES(8,'@','archaic',3);
INSERT INTO variant_levels VALUES(9,'x','invalid',4);
INSERT INTO regions VALUES(1,'',NULL);
INSERT INTO regions VALUES(5,'AU',NULL);
INSERT INTO regions VALUES(4,'CA',NULL);
INSERT INTO regions VALUES(3,'GB',NULL);
INSERT INTO regions VALUES(2,'US',NULL);
INSERT INTO spellings VALUES(2,'A','US','American');
INSERT INTO spellings VALUES(3,'B','GB','British(ise)');
INSERT INTO spellings VALUES(5,'C','CA','Canadian');
INSERT INTO spellings VALUES(6,'D','AU','Australian');
INSERT INTO spellings VALUES(4,'Z','GB','British(ize)');
INSERT INTO spellings VALUES(1,'_','','');
END;
