[lint]
extend-select = [
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "EXE",  # flake8-executable
    "FA",   # flake8-future-annotations
    "ICN",  # flake8-import-conventions 
    "ISC",  # flake8-implicit-str-concat
    "LOG",  # flake8-logging
    "G",    # flake8-logging-format
    "INP",  # flake8-import-conventions
    "PIE",  # flake8-pie 
    "PYI",  # flake8-pyi
    "SIM",  # flake8-simplify
    "SLOT", # flake8-slots
    "TID",  # flake8-tidy-imports
    "FLY",  # flynt
    "I",    # isort
    "PERF", # Perflint
    "PGH",  # pygrep-hooks
    "PL",
    "UP",   # pyupgrade
    "FURB", # refurb
    "RUF",  # Ruff-specific rules
]
ignore = [
    "B007",    # unused-loop-control-variable
    "B904",    # raise-without-from-inside-except
    "B905",    # zip-without-explicit-strict
    "PIE808",  # unnecessary-range-start
    "SIM102",  # collapsible-if
    "SIM105",  # suppressible-exception
    "SIM108",  # if-else-block-instead-of-if-exp
    "SIM115",  # open-file-with-context-handler
    "SIM118",  # in-dict-keys
    "I001",    # FIXME: unsorted-imports
    "PERF203", # try-except-in-loop
    "E402",    # module-import-not-at-top-of-file
    "E701",    # multiple-statements-on-one-line-colon
    "E741",    # ambiguous-variable-name
    "F401",    # unused-import
    "F403",    # undefined-local-with-import-star
    "F405",    # undefined-local-with-import-star-usage
    "F841",    # FIXME: unused-variable
    "PLC0415", # import-outside-top-level
    "PLR091",  # too-many-...
    "PLR2004", # magic-value-comparison
    "PLR2044", # empty-comment
    "PLR5501", # collapsible-else-if
    "PLW0603", # global-statement
    "PLW1641", # eq-without-hash
    "PLW2901", # redefined-loop-name
    "RUF023",  # unsorted-dunder-slots
    "RUF059",  # unused-unpacked-variable
]
