#!/bin/bash

shopt -s nullglob
set -e

rm -f *.twl

export LANG=C
export LC_ALL=C
export LC_CTYPE=C
export LC_COLLATE=C

FINAL=final

echo base

cat $FINAL/english-*.{10,20,35,40,50,55,60} $FINAL/special-* \
  | sort -u > en.wl0
cat en.wl0 $FINAL/american-*.{10,20,35,40,50,55,60} \
  | sort -u > en_US-w_accents.twl
cat en.wl0 $FINAL/british-*.{10,20,35,40,50,55,60} \
  | sort -u > en_GB-ise-w_accents.twl
cat en.wl0 $FINAL/british_z-*.{10,20,35,40,50,55,60} \
  | sort -u > en_GB-ize-w_accents.twl
cat en.wl0 $FINAL/canadian-*.{10,20,35,40,50,55,60} \
  | sort -u > en_CA-w_accents.twl
cat en_??-w_accents.twl \
  | sort -u > en-w_accents.twl

#cat en_GB-ise-w_accents.twl en_GB-ize-w_accents.twl
#  | sort -u > en_GB-w_accents.twl

cat $FINAL/variant_0-*.{10,20,35,40,50,55,60} \
  | sort -u > en-variant_0.wl0
cat en-variant_0.wl0 $FINAL/variant_1-*.{10,20,35,40,50,55,60} \
  | sort -u > en-variant_1.wl0
cat en-variant_1.wl0 $FINAL/variant_2-*.{10,20,35,40,50,55,60} \
  | sort -u > en-variant_2.wl0

cat $FINAL/british_variant_0-*.{10,20,35,40,50,55,60} \
  | sort -u > en_GB-variant_0.wl0
cat en_GB-variant_0.wl0 $FINAL/british_variant_1-*.{10,20,35,40,50,55,60} \
  | sort -u > en_GB-variant_1.wl0

cat $FINAL/canadian_variant_0-*.{10,20,35,40,50,55,60} \
  | sort -u > en_CA-variant_0.wl0
cat en_CA-variant_0.wl0 $FINAL/canadian_variant_1-*.{10,20,35,40,50,55,60} \
  | sort -u > en_CA-variant_1.wl0

echo deaccent

for f in *-w_accents.twl
do
  b=`basename $f -w_accents.twl`
  src/deaccent < $f | sort -u > $b-wo_accents.twl
  #cat $f $b-wo_accents.twl | sort -u > $b.twl
done

for f in en*-variant_*.wl0
do
  b=`basename $f .wl0`
  src/deaccent < $f > $b.wl1
  cat $f $b.wl1 | sort -u > $b.wl
done

echo common

# find the intersection of all *.twl word lists

cat *.twl | sort -u > en-common.wl.0
for f in *.twl
do
  comm -12 en-common.wl.0 $f > en-common.wl
  mv en-common.wl en-common.wl.0
done
mv en-common.wl.0 en-common.wl

echo finish

for f in *.twl
do
  b=`basename $f .twl`
  comm -13 en-common.wl $f > $b-only.wl
done
 
rm -f *.wl.* *.twl *.wl{0,1} *.vwl
cp -p *.wl aspell/
cp -p ../README aspell/doc/SCOWL-README
cat aspell/Copyright.in ../Copyright > aspell/Copyright


