#!/bin/bash

ASPELL=$HOME/aspell-0.60-cvs/inst/bin/aspell
HUNSPELL=/usr/local/bin/hunspell

set -e

export LANG=C
export LC_ALL=C
export LC_CTYPE=C
export LC_COLLATE=C

prep() {
  echo prep 

  cat misc/{offensive.1,offensive.2,profane.1} | sort -u > nosug

  cp en.aff eng_affix.dat

  cat << EOF > eng.dat
name eng
charset iso8859-1
special ' -*-
affix eng
EOF
}

doit() {
  echo creating en_$1.dic

  cat en-common.wl en_$1-wo_accents-only.wl | sort -u > en_$1.0

  comm en_$1.0 nosug -12 > en_$1-nosug.1

  comm en_$1.0 nosug -23 > en_$1.1

  $ASPELL -l ./eng munch-list < en_$1-nosug.1 | ./add-no-suggest > en_$1.2

  $ASPELL -l ./eng munch-list < en_$1.1 >> en_$1.2

  cat en.dic.supp >> en_$1.2

  wc -l en_$1.2 | cut -d' ' -f1 > en_$1.dic
  cat en_$1.2 | sort >> en_$1.dic

  cp en.aff en_$1.aff

  #echo check

  #hunspell -l -d ./en_$1 < en_$1.dic.0 > misspelled
}


prep

doit US
doit CA

rm eng*.dat nosug en_US*.? en_CA*.?
