#!/usr/bin/perl

use strict;
use warnings;

use utf8;

use open ':std' => ':encoding(utf-8)';

use lib 'sql/';
use make_list qw(%standard get_wordlist);

my $dict = $ARGV[0] or die "Usage: make_list <dict>";

my $parms = $standard{$dict} or die "Unknown dict: $dict\n";

my $words = get_wordlist("scowl.db", $parms);

foreach (@$words) {
    print "$_\n";
}
