#!/bin/sh

export LC_ALL=C
export LANG=C

to_sort() {
cat <<EOF
abbreviations
abbreviations-also
add-possessive
exclude.60
exclude.70
exclude.80
extra.60
hacker-exclude
letters
name-endings
name-endings.60
names-part
never-abbreviations
never-variant
not-possessive
not-upper
proper-names
roman-numerals
signature.35
signature.50
signature.60
signature.70
unix-terms
variant_1
variant_2
variant_3
mozilla-alan.60
marco-alan.60
marco-alan.70
marco.80
high-freq.60
high-freq.70
prefixes
phrase-parts
australian.35
chinese-names
cs.60
cs.70
neol2020
metric-units
EOF
}

for f in `to_sort`
do
    sort -u $f -o $f
done
