#!/bin/bash

set -e

GIT_VER=$1
PARMS_FILE=`pwd`/$2

SCOWL=${SCOWL:-`pwd`}

rm -rf aspell6-en-custom
cp -a $SCOWL/speller/aspell-custom aspell6-en-custom
cd aspell6-en-custom
. README.in.sh > README
rm README.in.sh
cat <<EOF > Copyright
The custom English dictionary for Aspell comes directly from SCOWL and is thus
under the same copyright terms as SCOWL.  The affix file is based on the
Ispell one, which is under the same copyright terms as Ispell.

EOF
sh $SCOWL/speller/Copyright.sh >> Copyright
mkdir lang
cp -a $SCOWL/speller/aspell/{en.dat,en_affix.dat,en_phonet.dat} lang/
mkdir doc

cat > en-custom.wl

./configure

make dist

mv aspell6-en-custom.tar.bz2 ..
cd ..
rm -r aspell6-en-custom


